# Generated by Django 4.2.3 on 2023-08-22 08:17

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("product", "0002_product_image"),
    ]

    operations = [
        migrations.RenameModel(old_name="Product", new_name="ProductMen",),
    ]
