# Generated by Django 4.2.3 on 2023-08-22 15:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0004_productwomen"),
    ]

    operations = [
        migrations.RemoveField(model_name="productmen", name="user",),
        migrations.RemoveField(model_name="productwomen", name="user",),
    ]
