# Generated by Django 4.2.4 on 2023-08-23 02:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0005_remove_productmen_user_remove_productwomen_user"),
    ]

    operations = [
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100)),
                ("price", models.TextField()),
                ("type", models.TextField()),
                ("image", models.ImageField(blank=True, null=True, upload_to="")),
                ("madeFor", models.TextField()),
            ],
        ),
        migrations.DeleteModel(name="ProductMen",),
        migrations.DeleteModel(name="ProductWomen",),
    ]
