# Generated by Django 4.2.4 on 2023-08-23 02:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0006_product_delete_productmen_delete_productwomen"),
    ]

    operations = [
        migrations.RenameField(
            model_name="product", old_name="madeFor", new_name="category",
        ),
    ]
