# Generated by Django 4.2.4 on 2023-08-23 03:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0008_category_alter_product_category"),
    ]

    operations = [
        migrations.RenameField(
            model_name="category", old_name="category", new_name="name",
        ),
    ]
