# Generated by Django 4.2.4 on 2023-08-23 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0010_type_alter_product_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="category", name="name", field=models.TextField(max_length=100),
        ),
        migrations.AlterField(
            model_name="type", name="name", field=models.TextField(max_length=100),
        ),
    ]
