# Generated by Django 4.2.4 on 2023-08-23 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0011_alter_category_name_alter_type_name"),
    ]

    operations = [
        migrations.CreateModel(
            name="UserData",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("Firstname", models.CharField(max_length=100)),
                ("Lastname", models.CharField(max_length=100)),
                ("job_role", models.CharField(max_length=100)),
                ("phonenumber", models.CharField(max_length=100)),
                ("address", models.CharField(max_length=100)),
                ("image", models.ImageField(blank=True, null=True, upload_to="")),
            ],
        ),
    ]
