# Generated by Django 4.2.4 on 2023-08-23 15:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0012_userdata"),
    ]

    operations = [
        migrations.RenameField(
            model_name="userdata", old_name="image", new_name="my_image",
        ),
    ]
