# Generated by Django 4.2.3 on 2023-08-31 15:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0015_productbuyerinfo"),
    ]

    operations = [
        migrations.DeleteModel(name="UserData",),
    ]
