# Generated by Django 4.2.4 on 2023-09-01 09:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0018_remove_product_user"),
    ]

    operations = [
        migrations.DeleteModel(name="ProductBuyerInfo",),
    ]
