# Generated by Django 4.2.4 on 2023-09-02 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0019_delete_productbuyerinfo"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="price",
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
