# Generated by Django 4.2.4 on 2023-09-01 10:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("purchase", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="productbuyerinfo", old_name="User", new_name="user",
        ),
        migrations.RemoveField(model_name="addtocart", name="User",),
        migrations.RemoveField(model_name="productbuyerinfo", name="date",),
        migrations.RemoveField(model_name="productbuyerinfo", name="product",),
        migrations.AddField(
            model_name="addtocart",
            name="cart_category",
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="addtocart",
            name="cart_image",
            field=models.ImageField(blank=True, null=True, upload_to=""),
        ),
        migrations.AddField(
            model_name="addtocart",
            name="cart_price",
            field=models.TextField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="addtocart",
            name="cart_title",
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="addtocart",
            name="cart_type",
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="productbuyerinfo",
            name="cart_product",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="purchase.addtocart",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="addtocart",
            name="user",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
