# Generated by Django 4.2.4 on 2023-09-01 10:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("purchase", "0002_rename_user_productbuyerinfo_user_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="productbuyerinfo",
            name="cart_product",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="purchase.addtocart",
            ),
        ),
    ]
