# Generated by Django 4.2.4 on 2023-09-01 10:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("purchase", "0003_alter_productbuyerinfo_cart_product"),
    ]

    operations = [
        migrations.RemoveField(model_name="addtocart", name="cart_image",),
    ]
