# Generated by Django 4.2.4 on 2023-09-01 10:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("purchase", "0004_remove_addtocart_cart_image"),
    ]

    operations = [
        migrations.RemoveField(model_name="addtocart", name="product",),
    ]
