# Generated by Django 4.2.4 on 2023-09-02 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("purchase", "0005_remove_addtocart_product"),
    ]

    operations = [
        migrations.AlterField(
            model_name="addtocart",
            name="cart_price",
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
    ]
