# Generated by Django 4.2.4 on 2023-09-02 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("purchase", "0006_alter_addtocart_cart_price"),
    ]

    operations = [
        migrations.RemoveField(model_name="productbuyerinfo", name="cart_product",),
        migrations.AddField(
            model_name="productbuyerinfo",
            name="total_price",
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
    ]
